import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Final

import yaml
from pydantic import BaseModel, ConfigDict, Field, ValidationError

from rich.panel import Panel
from rich.table import Table

from utils.console import configure_logging, console
from utils import fs
from utils.markdown import (
    assemble_codex_skill,
    assemble_cursor_rule,
    derive_description,
    ensure_trailing_newline,
    nonempty_str,
    normalize_text,
    render_front_matter,
)
from utils.slugs import (
    NUMBERED_COPY_PATTERN,
    SAFE_SLUG_PATTERN,
    slug_to_codex_name,
    validate_slug,
)

CODEX_RULE_MARKER: Final[str] = "# Generated by agent_sync from .agents/rules/"
MAX_DIFF_LINES: Final[int] = 20


class OutputFile(BaseModel):
    model_config = ConfigDict(frozen=True)

    target_path: Path
    content: str
    kind: str
    slug: str
    source_path: Path | None


class DiffEntry(BaseModel):
    model_config = ConfigDict(frozen=True)

    output: OutputFile
    existing: str | None


class PlatformSettings(BaseModel):
    model_config = ConfigDict(extra="allow", strict=True)

    model: str | None = None


class AgentModelOverride(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)

    claude: str | None = None
    cursor: str | None = None
    codex: str | None = None


class SkillFrontMatter(BaseModel):
    model_config = ConfigDict(extra="allow", strict=True)

    name: str | None = None
    description: str | None = None


class CommandFrontMatter(BaseModel):
    model_config = ConfigDict(extra="allow", strict=True, populate_by_name=True)

    allowed_tools: str | None = Field(default=None, alias="allowed-tools")
    variants: dict[str, str] | None = None


class AgentFrontMatter(BaseModel):
    model_config = ConfigDict(extra="allow", strict=True)

    name: str | None = None
    description: str | None = None
    tools: str | None = None
    model: str | None = None


class RuleFrontMatter(BaseModel):
    model_config = ConfigDict(extra="allow", strict=True)

    starlark: str | None = None


def main() -> int:
    """Resolve the repository root then sync .agents into the Claude/Cursor/Codex folders."""

    parser = argparse.ArgumentParser(description="Sync .agents into Claude/Cursor/Codex folders.")
    fs.add_root_arguments(parser)
    parser.add_argument("--dry-run", action="store_true", help="Report diffs without writing.")
    args = parser.parse_args()

    configure_logging()

    fs.set_root_from_args(args)

    if not fs.agents_dir().exists():
        console.print(f"[red]Error:[/red] Missing agents directory: {fs.agents_dir()}")

        return 2

    platform_settings = load_platform_settings()
    agent_model_overrides = load_agent_model_overrides()
    outputs = generate_outputs(platform_settings, agent_model_overrides)
    diffs = compute_diffs(outputs)
    stale_paths = compute_stale_paths(outputs, platform_settings)

    if not diffs and not stale_paths:
        console.print(Panel("No differences found.", style="green"))

        return 0

    if args.dry_run:
        report_diffs(diffs, stale_paths)

        return 1

    for diff in diffs:
        fs.write_text(diff.output.target_path, diff.output.content)
        status = "created" if diff.existing is None else "updated"
        console.print(f"  [green]✓[/green] {status}: {diff.output.target_path}")

    for stale_path in stale_paths:
        fs.delete_path(stale_path)
        console.print(f"  [green]✓[/green] deleted: {stale_path}")

    dedupe_outputs()

    console.print()
    console.print(
        Panel(
            f"Sync complete. {len(diffs)} file(s) written, {len(stale_paths)} stale path(s) deleted.",
            style="green",
        )
    )

    return 0


def settings_dir() -> Path:
    """Return the .agents/settings directory under the configured root."""

    return fs.agents_dir() / "settings"


def models_dir() -> Path:
    """Return the .agents/models directory under the configured root."""

    return fs.agents_dir() / "models"


def load_json_object(path: Path, model: type[BaseModel]) -> dict | None:
    """Read a JSON object from path and validate it against model, warning and returning None on failure."""

    raw = fs.read_text(path)
    if raw is None:
        return None

    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        console.print(f"[yellow]Warning:[/yellow] Invalid JSON in {path}: {exc}")

        return None

    if not isinstance(data, dict):
        console.print(f"[yellow]Warning:[/yellow] {path} is not a JSON object; ignoring.")

        return None

    return validate_front_matter(data, model, str(path))


def load_platform_settings() -> dict[str, dict]:
    """Load each .agents/settings/<platform>.json, validating its top-level shape."""

    settings: dict[str, dict] = {}
    if not settings_dir().exists():
        return settings

    for path in sorted(settings_dir().glob("*.json")):
        data = load_json_object(path, PlatformSettings)
        if data is not None:
            settings[path.stem] = data

    return settings


def load_agent_model_overrides() -> dict[str, dict[str, str]]:
    """Load each .agents/models/<agent-slug>.json mapping agent slug to per-platform model."""

    overrides: dict[str, dict[str, str]] = {}
    if not models_dir().exists():
        return overrides

    for path in sorted(models_dir().glob("*.json")):
        slug = validate_slug(path.stem, path)
        data = load_json_object(path, AgentModelOverride)
        if data is not None:
            overrides[slug] = {k: v for k, v in data.items() if isinstance(v, str) and v}

    return overrides


def validate_front_matter(data: dict, model: type[BaseModel], source: str) -> dict | None:
    """Validate front matter data against a Pydantic model, returning None on failure so callers can skip."""

    try:
        model.model_validate(data)
    except ValidationError as exc:
        console.print(f"[yellow]Warning:[/yellow] Invalid front matter in {source}: {exc}")

        return None

    return data


def parse_markdown_file(path: Path, model: type[BaseModel] | None = None) -> tuple[dict, str]:
    """Parse markdown front matter and body content."""

    content = fs.read_text(path)
    if content is None:
        return {}, ""

    front_matter: dict = {}
    body = content

    lines = content.splitlines()
    if lines and lines[0] == "---":
        end_index = -1
        for index, line in enumerate(lines[1:], start=1):
            if line == "---":
                end_index = index
                break

        if end_index == -1:
            console.print(f"[yellow]Warning:[/yellow] Unterminated front matter in {path}.")
        else:
            front_matter_content = "\n".join(lines[1:end_index]).strip()
            body = "\n".join(lines[end_index + 1 :])
            if front_matter_content:
                raw_data = yaml.safe_load(front_matter_content) or {}
                if not isinstance(raw_data, dict):
                    console.print(f"[yellow]Warning:[/yellow] Invalid front matter in {path}.")
                elif model is None:
                    front_matter = raw_data
                else:
                    front_matter = validate_front_matter(raw_data, model, str(path)) or {}

    return front_matter, normalize_text(body)


def generate_outputs(
    platform_settings: dict[str, dict],
    agent_model_overrides: dict[str, dict[str, str]],
) -> list[OutputFile]:
    """Generate all output files from .agents sources."""

    outputs: list[OutputFile] = []
    outputs.extend(generate_skill_outputs())
    outputs.extend(generate_command_outputs())
    outputs.extend(generate_agent_outputs(platform_settings, agent_model_overrides))
    outputs.extend(generate_rule_outputs())
    outputs.extend(generate_hook_outputs())
    outputs.extend(generate_settings_outputs(platform_settings))

    return outputs


def generate_skill_outputs() -> list[OutputFile]:
    """Sync .agents/skills/<slug>/SKILL.md to .claude/skills/, .cursor/skills/, and .codex/skills/."""

    outputs: list[OutputFile] = []
    skills_dir = fs.agents_dir() / "skills"
    if not skills_dir.exists():
        return outputs

    for skill_dir in sorted(skills_dir.iterdir()):
        if not skill_dir.is_dir():
            continue

        slug = validate_slug(skill_dir.name, skill_dir)
        source_path = skill_dir / "SKILL.md"
        if not source_path.exists():
            console.print(f"[yellow]Warning:[/yellow] Missing SKILL.md in {skill_dir}.")
            continue

        front_matter, content = parse_markdown_file(source_path, SkillFrontMatter)
        source_content = fs.read_text(source_path) or ""

        codex_name = nonempty_str(front_matter.get("name")) or slug_to_codex_name(slug)
        if not SAFE_SLUG_PATTERN.match(codex_name):
            console.print(
                f"[yellow]Warning:[/yellow] Invalid codex skill name '{codex_name}' in {source_path}; using '{slug_to_codex_name(slug)}'."
            )
            codex_name = slug_to_codex_name(slug)

        codex_description = nonempty_str(front_matter.get("description")) or derive_description(content)

        skill_dirs = (("cursor", slug), ("claude", slug), ("codex", codex_name))

        skill_md_content = {
            "cursor": ensure_trailing_newline(source_content),
            "claude": ensure_trailing_newline(source_content),
            "codex": assemble_codex_skill(content, codex_name, codex_description),
        }
        for platform, dir_name in skill_dirs:
            outputs.append(
                OutputFile(
                    target_path=fs.root() / f".{platform}" / "skills" / dir_name / "SKILL.md",
                    content=skill_md_content[platform],
                    kind=f"{platform}_skill",
                    slug=slug,
                    source_path=source_path,
                )
            )

        for asset_path in sorted(skill_dir.rglob("*")):
            if not asset_path.is_file() or asset_path.name == "SKILL.md":
                continue
            asset_content = fs.read_text(asset_path)
            if asset_content is None:
                continue
            relative = asset_path.relative_to(skill_dir)
            for platform, dir_name in skill_dirs:
                outputs.append(
                    OutputFile(
                        target_path=fs.root() / f".{platform}" / "skills" / dir_name / relative,
                        content=ensure_trailing_newline(asset_content),
                        kind=f"{platform}_skill_asset",
                        slug=slug,
                        source_path=asset_path,
                    )
                )

    return outputs


def generate_command_outputs() -> list[OutputFile]:
    """Generate Claude and Cursor command files for each command markdown file."""

    outputs: list[OutputFile] = []
    commands_dir = fs.agents_dir() / "commands"
    if not commands_dir.exists():
        return outputs

    for path in sorted(commands_dir.glob("*.md")):
        slug = validate_slug(path.stem, path)
        front_matter, content = parse_markdown_file(path, CommandFrontMatter)
        raw_variants = front_matter.get("variants")
        variants = raw_variants if isinstance(raw_variants, dict) else {}

        claude_body = normalize_text(variants.get("claude", content) or content)
        cursor_body = normalize_text(variants.get("cursor", content) or content)
        claude_front_matter = dict(front_matter)
        claude_front_matter.pop("variants", None)

        if claude_front_matter:
            claude_output = render_front_matter(claude_front_matter, claude_body)
        else:
            claude_output = ensure_trailing_newline(claude_body)

        outputs.append(
            OutputFile(
                target_path=fs.root() / ".claude" / "commands" / f"{slug}.md",
                content=claude_output,
                kind="claude_command",
                slug=slug,
                source_path=path,
            )
        )
        outputs.append(
            OutputFile(
                target_path=fs.root() / ".cursor" / "commands" / f"{slug}.md",
                content=ensure_trailing_newline(cursor_body),
                kind="cursor_command",
                slug=slug,
                source_path=path,
            )
        )

    return outputs


def generate_agent_outputs(
    platform_settings: dict[str, dict],
    agent_model_overrides: dict[str, dict[str, str]],
) -> list[OutputFile]:
    """Generate Claude and Cursor agent files with per-platform model resolution."""

    outputs: list[OutputFile] = []
    agents_subdir = fs.agents_dir() / "agents"
    if not agents_subdir.exists():
        return outputs

    for path in sorted(agents_subdir.glob("*.md")):
        slug = validate_slug(path.stem, path)
        front_matter, content = parse_markdown_file(path, AgentFrontMatter)
        source_front_matter = dict(front_matter)
        source_front_matter.pop("model", None)

        for platform in ("claude", "cursor"):
            platform_front_matter = dict(source_front_matter)
            model = resolve_agent_model(slug, platform, platform_settings, agent_model_overrides)
            if model:
                platform_front_matter["model"] = model

            agent_content = render_front_matter(platform_front_matter, content)
            outputs.append(
                OutputFile(
                    target_path=fs.root() / f".{platform}" / "agents" / f"{slug}.md",
                    content=agent_content,
                    kind=f"{platform}_agent",
                    slug=slug,
                    source_path=path,
                )
            )

    return outputs


def generate_rule_outputs() -> list[OutputFile]:
    """Sync .agents/rules/<name>.md to .claude/rules/*.md, .cursor/rules/*.mdc, and Starlark .codex/rules/*.rules."""

    outputs: list[OutputFile] = []
    rules_dir = fs.agents_dir() / "rules"
    if not rules_dir.exists():
        return outputs

    for path in sorted(rules_dir.glob("*.md")):
        slug = validate_slug(path.stem, path)
        front_matter, body = parse_markdown_file(path, RuleFrontMatter)
        if body.strip():
            outputs.append(
                OutputFile(
                    target_path=fs.root() / ".claude" / "rules" / f"{slug}.md",
                    content=ensure_trailing_newline(body),
                    kind="claude_rule",
                    slug=slug,
                    source_path=path,
                )
            )
            outputs.append(
                OutputFile(
                    target_path=fs.root() / ".cursor" / "rules" / f"{slug}.mdc",
                    content=assemble_cursor_rule(body, always_apply=True),
                    kind="cursor_rule",
                    slug=slug,
                    source_path=path,
                )
            )

        starlark = front_matter.get("starlark")
        if isinstance(starlark, str) and starlark.strip():
            content = f"{CODEX_RULE_MARKER}{path.name}\n{starlark.strip()}"
            outputs.append(
                OutputFile(
                    target_path=fs.root() / ".codex" / "rules" / f"{slug}.rules",
                    content=ensure_trailing_newline(content),
                    kind="codex_rule",
                    slug=slug,
                    source_path=path,
                )
            )

    return outputs


def generate_hook_outputs() -> list[OutputFile]:
    """Sync .agents/hooks/* scripts to .claude/hooks/ and .cursor/hooks/."""

    outputs: list[OutputFile] = []
    hooks_dir = fs.agents_dir() / "hooks"
    if not hooks_dir.exists():
        return outputs

    for path in sorted(hooks_dir.iterdir()):
        if not path.is_file():
            continue
        content = fs.read_text(path)
        if content is None:
            continue
        for platform in ("claude", "cursor"):
            outputs.append(
                OutputFile(
                    target_path=fs.root() / f".{platform}" / "hooks" / path.name,
                    content=ensure_trailing_newline(content),
                    kind=f"{platform}_hook",
                    slug=path.stem,
                    source_path=path,
                )
            )

    return outputs


def generate_settings_outputs(platform_settings: dict[str, dict]) -> list[OutputFile]:
    """Sync .agents/settings/claude.json verbatim to .claude/settings.json."""

    outputs: list[OutputFile] = []
    claude_settings = platform_settings.get("claude")
    if claude_settings is None:
        return outputs

    outputs.append(
        OutputFile(
            target_path=fs.root() / ".claude" / "settings.json",
            content=ensure_trailing_newline(json.dumps(claude_settings, indent=2)),
            kind="claude_settings",
            slug="claude",
            source_path=settings_dir() / "claude.json",
        )
    )

    return outputs


def compute_diffs(outputs: list[OutputFile]) -> list[DiffEntry]:
    """Compare generated outputs against on-disk files and return entries that differ."""

    diffs: list[DiffEntry] = []
    for output in outputs:
        existing = fs.read_text(output.target_path)
        if existing is None or existing != output.content or missing_exec_bit(output):
            diffs.append(DiffEntry(output=output, existing=existing))

    return diffs


def missing_exec_bit(output: OutputFile) -> bool:
    """Report whether an executable output exists on disk without its exec bit, so write re-applies chmod."""

    target = output.target_path
    if not fs.is_executable_output(target, output.content):
        return False

    return target.exists() and not target.stat().st_mode & 0o111


def compute_stale_paths(
    outputs: list[OutputFile],
    platform_settings: dict[str, dict],
) -> list[Path]:
    """Find generated files/directories that no longer map to .agents sources."""

    expected_paths = {output.target_path for output in outputs}
    expected_skill_dirs = {
        output.target_path.parent
        for output in outputs
        if output.kind in {"codex_skill", "claude_skill", "cursor_skill"}
    }
    stale_paths: set[Path] = set()

    managed_file_globs = (
        (fs.root() / ".cursor" / "rules", "*.mdc"),
        (fs.root() / ".claude" / "rules", "*.md"),
        (fs.root() / ".cursor" / "commands", "*.md"),
        (fs.root() / ".claude" / "commands", "*.md"),
        (fs.root() / ".cursor" / "agents", "*.md"),
        (fs.root() / ".claude" / "agents", "*.md"),
        (fs.root() / ".cursor" / "hooks", "*"),
        (fs.root() / ".claude" / "hooks", "*"),
        (fs.root() / ".cursor" / "skills", "**/*"),
        (fs.root() / ".claude" / "skills", "**/*"),
        (fs.root() / ".codex" / "skills", "**/*"),
    )

    for directory, pattern in managed_file_globs:
        if not directory.exists():
            continue

        for path in directory.glob(pattern):
            if path.is_file() and path not in expected_paths:
                stale_paths.add(path)

    codex_rules_dir = fs.root() / ".codex" / "rules"
    if codex_rules_dir.exists():
        for path in codex_rules_dir.glob("*.rules"):
            if not path.is_file() or path in expected_paths:
                continue
            head = fs.read_text(path)
            if head is not None and head.startswith(CODEX_RULE_MARKER):
                stale_paths.add(path)

    settings_path = fs.root() / ".claude" / "settings.json"
    if "claude" in platform_settings and settings_path.exists() and settings_path not in expected_paths:
        stale_paths.add(settings_path)

    for platform in ("codex", "claude", "cursor"):
        skills_subdir = fs.root() / f".{platform}" / "skills"
        if not skills_subdir.exists():
            continue
        for path in skills_subdir.iterdir():
            if path.is_dir() and path not in expected_skill_dirs:
                stale_paths.add(path)

    return sorted(stale_paths, key=str)


def report_diffs(diffs: list[DiffEntry], stale_paths: list[Path]) -> None:
    """Print a table and unified diffs for everything that would change in a dry run."""

    console.print(Panel("Differences detected", style="yellow"))
    table = Table(show_header=True, header_style="bold")
    table.add_column("Target")
    table.add_column("Kind")
    table.add_column("Status")

    for diff in diffs:
        status = "missing" if diff.existing is None else "changed"
        table.add_row(str(diff.output.target_path), diff.output.kind, status)

    for stale_path in stale_paths:
        kind = "directory" if stale_path.is_dir() else "generated"
        table.add_row(str(stale_path), kind, "stale")

    console.print(table)

    for diff in diffs:
        console.print()
        console.print(Panel(diff_summary(diff), title=str(diff.output.target_path)))

    for stale_path in stale_paths:
        console.print()
        console.print(Panel("will be deleted", title=str(stale_path)))


def diff_summary(diff: DiffEntry) -> str:
    """Produce a unified diff between existing and expected content."""

    existing = diff.existing or ""
    expected = diff.output.content
    lines = list(
        difflib.unified_diff(
            existing.splitlines(),
            expected.splitlines(),
            fromfile="current",
            tofile="expected",
            lineterm="",
        )
    )

    if not lines:
        if existing != expected:
            return "(trailing newline difference)"

        return "(no changes)"

    return "\n".join(lines[:MAX_DIFF_LINES])


def resolve_agent_model(
    agent_slug: str,
    platform: str,
    platform_settings: dict[str, dict],
    agent_model_overrides: dict[str, dict[str, str]],
) -> str | None:
    """Pick the per-agent override for this platform; fall back to the platform-wide default."""

    override = agent_model_overrides.get(agent_slug, {}).get(platform)
    default = platform_settings.get(platform, {}).get("model")

    return nonempty_str(override) or nonempty_str(default)


def dedupe_outputs() -> None:
    """Remove OS-created duplicate rule files in the generated Claude/Cursor rule directories."""

    for directory in (fs.root() / ".cursor" / "rules", fs.root() / ".claude" / "rules"):
        dedupe_directory(directory)


def dedupe_directory(directory: Path) -> None:
    """Remove OS-created duplicate files whose name ends with a space and a number (e.g. "name 2.md")."""

    if not directory.exists():
        return

    for path in sorted(directory.iterdir()):
        if path.is_file() and NUMBERED_COPY_PATTERN.search(path.stem):
            path.unlink(missing_ok=True)
            fs.TEXT_CACHE.pop(path, None)


if __name__ == "__main__":
    sys.exit(main())
