import pytest

from agent_sync.generation.artifact import generate_agents, generate_hooks
from agent_sync.generation.rule import (
    generate_codex_rules,
    generate_rule_links,
    generate_shared_rule_outputs,
)
from agent_sync.models.output import ArtifactKind, GeneratedFile, GeneratedLink, Provider
from agent_sync.workspace import Workspace
from tests.factories import RuleFrontMatterFactory, materialize_rule, load_context


class TestDocumentGeneration:
    """Test that agents, rules, and hooks use their artifact formats."""

    def test_agent_model_override_precedes_provider_default(
        self,
        workspace: Workspace,
    ) -> None:
        """Test that agent-specific models override provider-wide settings."""

        agents_dir = workspace.agents_dir / "agents"
        agents_dir.mkdir()
        (agents_dir / "review.md").write_text("---\nname: review\n---\n\nReview.\n")
        workspace.settings_dir.mkdir()
        (workspace.settings_dir / "claude.json").write_text('{"model":"default"}')
        workspace.models_dir.mkdir()
        (workspace.models_dir / "review.json").write_text('{"claude":"override","cursor":"cursor-model"}')

        context = load_context(workspace)
        outputs = [
            *generate_agents(context, Provider.CLAUDE),
            *generate_agents(context, Provider.CURSOR),
        ]
        files = {output.provider: output.content for output in outputs if isinstance(output, GeneratedFile)}

        assert "model: override" in files[Provider.CLAUDE]
        assert "model: cursor-model" in files[Provider.CURSOR]

        assert all(
            "\n---\n\n<!-- Generated by [Agent Sync Action]"
            "(https://github.com/julien777z/agent-sync-action). "
            "Do not edit this file directly. -->\n\nReview." in content
            for content in files.values()
        )

    def test_rules_normalize_sources_and_generate_links(
        self,
        workspace: Workspace,
    ) -> None:
        """Test that one normalized rule owns both provider links."""

        source = workspace.agents_dir / "rules/python.md"
        materialize_rule(source, RuleFrontMatterFactory.build(name="removed"))
        context = load_context(workspace)
        outputs = [
            *generate_shared_rule_outputs(context),
            *generate_rule_links(context, Provider.CLAUDE),
            *generate_rule_links(context, Provider.CURSOR),
        ]
        source_output = next(
            output for output in outputs if isinstance(output, GeneratedFile) and output.target_path == source
        )

        links = [output for output in outputs if isinstance(output, GeneratedLink)]

        assert source_output.content.startswith("---\ndescription: A rule.\nalwaysApply: true\n---\n")
        assert "name:" not in source_output.content
        assert {link.link_target for link in links} == {source}
        assert {link.target_path.suffix for link in links} == {".md", ".mdc"}

    def test_codex_rules_render_starlark_without_markdown_body(
        self,
        workspace: Workspace,
    ) -> None:
        """Test that a Starlark-only rule still generates its Codex output."""

        rules_dir = workspace.agents_dir / "rules"
        rules_dir.mkdir()
        source = rules_dir / "git.md"
        source.write_text('---\nstarlark: |\n  allow_rule(prefix_rule = ["git", "status"])\n' "---\n")

        context = load_context(workspace)
        outputs = generate_codex_rules(context, Provider.CODEX)

        assert len(outputs) == 1
        assert isinstance(outputs[0], GeneratedFile)
        assert outputs[0].target_path == workspace.root / ".codex/rules/git.rules"

        assert outputs[0].content.startswith(
            "# Generated by [Agent Sync Action]"
            "(https://github.com/julien777z/agent-sync-action). "
            "Do not edit this file directly.\n"
            "# Source: .agents/rules/git.md\n"
        )
        assert 'allow_rule(prefix_rule = ["git", "status"])' in outputs[0].content
        shared_outputs = generate_shared_rule_outputs(context)

        assert len(shared_outputs) == 1
        assert shared_outputs[0].artifact is ArtifactKind.INSTRUCTIONS
        assert not generate_rule_links(context, Provider.CLAUDE)
        assert not generate_rule_links(context, Provider.CURSOR)

    @pytest.mark.parametrize("authored_key", ["globs", "paths"])
    def test_rules_mirror_one_authored_scope_across_provider_keys(
        self,
        workspace: Workspace,
        authored_key: str,
    ) -> None:
        """Test that a scope authored under either key is emitted under both."""

        source = workspace.agents_dir / "rules/python.md"
        source.parent.mkdir(parents=True)
        source.write_text(f'---\n{authored_key}: "**/*.py"\n---\n\n# Rule\n')

        context = load_context(workspace)
        outputs = generate_shared_rule_outputs(context)
        normalized = next(
            output for output in outputs if isinstance(output, GeneratedFile) and output.target_path == source
        )

        assert "globs: '**/*.py'\n" in normalized.content
        assert "paths: '**/*.py'\n" in normalized.content

    def test_rules_scope_annotation_reads_a_paths_only_rule(
        self,
        workspace: Workspace,
    ) -> None:
        """Test that a Claude-style paths scope annotates the root instructions."""

        source = workspace.agents_dir / "rules/python.md"
        source.parent.mkdir(parents=True)
        source.write_text('---\npaths: ["**/*.py", "**/*.pyi"]\nalwaysApply: false\n---\n\n# Rule\n')

        context = load_context(workspace)
        instructions = next(
            output
            for output in generate_shared_rule_outputs(context)
            if isinstance(output, GeneratedFile) and output.artifact is ArtifactKind.INSTRUCTIONS
        )

        assert "> Applies only to files matching: `**/*.py`, `**/*.pyi`" in instructions.content

    def test_hooks_preserve_executable_intent(self, workspace: Workspace) -> None:
        """Test that shell and shebang hooks are marked executable."""

        hooks_dir = workspace.agents_dir / "hooks"
        hooks_dir.mkdir()
        (hooks_dir / "check").write_text("#!/usr/bin/env python3\nprint('ok')\n")

        context = load_context(workspace)
        outputs = [
            *generate_hooks(context, Provider.CLAUDE),
            *generate_hooks(context, Provider.CURSOR),
        ]

        assert outputs
        assert all(isinstance(output, GeneratedFile) and output.executable for output in outputs)
