import pytest

from agent_sync.generation.artifact import generate_agents, generate_hooks
from agent_sync.generation.rule import (
    generate_codex_rules,
    generate_rule_mirrors,
    generate_shared_rule_outputs,
)
from agent_sync.models.output import ArtifactKind, GeneratedFile, Provider
from agent_sync.workspace import Workspace
from tests.factories import RuleFrontMatterFactory, materialize_rule, load_context


class TestDocumentGeneration:
    """Test that agents, rules, and hooks use their artifact formats."""

    def test_agent_model_override_precedes_provider_default(
        self,
        workspace: Workspace,
    ) -> None:
        """Test that agent-specific models override provider-wide settings."""

        agents_dir = workspace.agents_dir / "agents"
        agents_dir.mkdir()
        (agents_dir / "review.md").write_text("---\nname: review\n---\n\nReview.\n")
        workspace.settings_dir.mkdir()
        (workspace.settings_dir / "claude.json").write_text('{"model":"default"}')
        workspace.models_dir.mkdir()
        (workspace.models_dir / "review.json").write_text('{"claude":"override","cursor":"cursor-model"}')

        context = load_context(workspace)
        outputs = [
            *generate_agents(context, Provider.CLAUDE),
            *generate_agents(context, Provider.CURSOR),
        ]
        files = {output.provider: output.content for output in outputs if isinstance(output, GeneratedFile)}

        assert "model: override" in files[Provider.CLAUDE]
        assert "model: cursor-model" in files[Provider.CURSOR]

        assert all(
            "\n---\n\n<!-- Generated by [Agent Sync Action]"
            "(https://github.com/julien777z/agent-sync-action). "
            "Do not edit this file directly. -->\n\nReview." in content
            for content in files.values()
        )

    def test_scoped_rules_generate_provider_files_without_changing_sources(
        self,
        workspace: Workspace,
    ) -> None:
        """Test that provider mirrors own scoped bodies while canonical text stays intact."""

        source = workspace.agents_dir / "rules/python.md"
        materialize_rule(source, RuleFrontMatterFactory.build(name="removed", always_apply=False))
        original = source.read_text()
        context = load_context(workspace)
        outputs = [
            *generate_shared_rule_outputs(context),
            *generate_rule_mirrors(context, Provider.CLAUDE),
            *generate_rule_mirrors(context, Provider.CURSOR),
        ]
        mirrors = [
            output
            for output in outputs
            if isinstance(output, GeneratedFile) and output.artifact is ArtifactKind.RULE
        ]

        assert source.read_text() == original
        assert len(mirrors) == 2
        assert {mirror.target_path.suffix for mirror in mirrors} == {".md", ".mdc"}
        assert all("Always be ruling." in mirror.content for mirror in mirrors)
        assert all("Generated by [Agent Sync Action]" in mirror.content for mirror in mirrors)
        assert all("name:" not in mirror.content for mirror in mirrors)

    def test_codex_rules_render_starlark_without_markdown_body(
        self,
        workspace: Workspace,
    ) -> None:
        """Test that a Starlark-only rule still generates its Codex output."""

        rules_dir = workspace.agents_dir / "rules"
        rules_dir.mkdir()
        source = rules_dir / "git.md"
        source.write_text('---\nstarlark: |\n  allow_rule(prefix_rule = ["git", "status"])\n' "---\n")

        context = load_context(workspace)
        outputs = generate_codex_rules(context, Provider.CODEX)

        assert len(outputs) == 1
        assert isinstance(outputs[0], GeneratedFile)
        assert outputs[0].target_path == workspace.root / ".codex/rules/git.rules"

        assert outputs[0].content.startswith(
            "# Generated by [Agent Sync Action]"
            "(https://github.com/julien777z/agent-sync-action). "
            "Do not edit this file directly.\n"
            "# Source: .agents/rules/git.md\n"
        )
        assert 'allow_rule(prefix_rule = ["git", "status"])' in outputs[0].content
        shared_outputs = generate_shared_rule_outputs(context)

        assert not shared_outputs
        assert not generate_rule_mirrors(context, Provider.CLAUDE)
        assert not generate_rule_mirrors(context, Provider.CURSOR)

    @pytest.mark.parametrize("authored_key", ["globs", "paths"])
    def test_rules_mirror_one_authored_scope_across_provider_keys(
        self,
        workspace: Workspace,
        authored_key: str,
    ) -> None:
        """Test that a scope authored under either key is emitted under both."""

        source = workspace.agents_dir / "rules/python.md"
        source.parent.mkdir(parents=True)
        source.write_text(f'---\n{authored_key}: "**/*.py"\nalwaysApply: false\n---\n\n# Rule\n')

        context = load_context(workspace)
        mirrors = generate_rule_mirrors(context, Provider.CLAUDE)

        assert len(mirrors) == 1
        assert isinstance(mirrors[0], GeneratedFile)
        assert "globs: '**/*.py'\n" in mirrors[0].content
        assert "paths: '**/*.py'\n" in mirrors[0].content

    def test_rules_scope_annotation_reads_a_paths_only_rule(
        self,
        workspace: Workspace,
    ) -> None:
        """Test that a Claude-style paths scope annotates the root instructions."""

        source = workspace.agents_dir / "rules/python.md"
        source.parent.mkdir(parents=True)
        source.write_text('---\npaths: ["**/*.py", "**/*.pyi"]\nalwaysApply: false\n---\n\n# Rule\n')

        context = load_context(workspace)
        instructions = next(
            output
            for output in generate_shared_rule_outputs(context)
            if isinstance(output, GeneratedFile) and output.artifact is ArtifactKind.INSTRUCTIONS
        )

        assert (
            "Read `.agents/rules/python.md` for files matching `**/*.py`, `**/*.pyi`" in instructions.content
        )

    def test_hooks_preserve_executable_intent(self, workspace: Workspace) -> None:
        """Test that shell and shebang hooks are marked executable."""

        hooks_dir = workspace.agents_dir / "hooks"
        hooks_dir.mkdir()
        (hooks_dir / "check").write_text("#!/usr/bin/env python3\nprint('ok')\n")

        context = load_context(workspace)
        outputs = [
            *generate_hooks(context, Provider.CLAUDE),
            *generate_hooks(context, Provider.CURSOR),
        ]

        assert outputs
        assert all(isinstance(output, GeneratedFile) and output.executable for output in outputs)
