import json
import tomllib


from agent_sync.generation.setting import generate_claude_settings
from agent_sync.models.output import GeneratedFile, Provider
from agent_sync.reconciliation import mirror_providers
from agent_sync.workspace import Workspace
from tests.factories import RuleFrontMatterFactory, materialize_rule, load_context


class TestSettingsGeneration:
    """Test that synchronized settings fully own generated provider files."""

    def test_claude_settings_render_complete_json(self, workspace: Workspace) -> None:
        """Test that Claude settings preserve validated provider keys."""

        workspace.settings_dir.mkdir()
        (workspace.settings_dir / "claude.json").write_text(
            '{"$comment":"source comment","model":"sonnet",'
            '"permissions":{"allow":["Read"]},'
            '"features":{"default_mode_request_user_input":true,"experimental-feature":false}}'
        )

        outputs = generate_claude_settings(load_context(workspace), Provider.CLAUDE)

        assert len(outputs) == 1
        assert isinstance(outputs[0], GeneratedFile)
        assert json.loads(outputs[0].content) == {
            "$comment": (
                "Generated by [Agent Sync Action]"
                "(https://github.com/julien777z/agent-sync-action). "
                "Do not edit this file directly."
            ),
            "model": "sonnet",
            "permissions": {"allow": ["Read"]},
            "features": {
                "default_mode_request_user_input": True,
                "experimental-feature": False,
            },
        }

    def test_codex_capacity_overwrites_existing_toml(
        self,
        workspace: Workspace,
    ) -> None:
        """Test that generated instructions determine Codex document capacity."""

        materialize_rule(
            workspace.agents_dir / "rules/project.md",
            RuleFrontMatterFactory.build(name="removed"),
            body="# Project Rules\n\nKeep changes focused.",
        )

        workspace.settings_dir.mkdir(parents=True)
        settings_path = workspace.settings_dir / "codex.json"
        settings_path.write_text(
            '{"model":"gpt-5","project_doc_max_bytes":1,'
            '"features":{"default_mode_request_user_input":true}}'
        )

        config_path = workspace.root / ".codex/config.toml"
        config_path.parent.mkdir()
        config_path.write_text('model_reasoning_effort = "high"\n')

        assert mirror_providers(workspace, dry_run=False) is False

        instructions = (workspace.root / "AGENTS.md").read_text()
        capacity = len(instructions.encode("utf-8"))
        canonical = json.loads(settings_path.read_text())
        config_content = config_path.read_text()
        native = tomllib.loads(config_path.read_text())

        assert canonical == {
            "model": "gpt-5",
            "project_doc_max_bytes": capacity,
            "features": {"default_mode_request_user_input": True},
        }

        assert config_content.startswith(
            "# Generated by [Agent Sync Action]"
            "(https://github.com/julien777z/agent-sync-action). "
            "Do not edit this file directly.\n"
        )
        assert native == canonical
        assert "model_reasoning_effort" not in native
        assert mirror_providers(workspace, dry_run=True) is False

    def test_codex_features_accept_arbitrary_names(self, workspace: Workspace) -> None:
        """Test that arbitrary Codex feature names are synchronized unchanged."""

        workspace.settings_dir.mkdir()
        settings_path = workspace.settings_dir / "codex.json"
        settings_path.write_text(
            '{"project_doc_max_bytes":1,"features":'
            '{"default_mode_request_user_input":true,"experimental-feature":false}}'
        )

        assert mirror_providers(workspace, dry_run=False) is False

        canonical = json.loads(settings_path.read_text())
        native = tomllib.loads((workspace.root / ".codex/config.toml").read_text())

        assert canonical["features"] == {
            "default_mode_request_user_input": True,
            "experimental-feature": False,
        }
        assert native["features"] == canonical["features"]
        assert mirror_providers(workspace, dry_run=True) is False

    def test_invalid_existing_toml_is_overwritten(self, workspace: Workspace) -> None:
        """Test that existing Codex content never affects generated settings."""

        workspace.settings_dir.mkdir()
        (workspace.settings_dir / "codex.json").write_text('{"project_doc_max_bytes":1}')

        config_path = workspace.root / ".codex/config.toml"
        config_path.parent.mkdir()
        config_path.write_text("invalid = [\n")

        assert mirror_providers(workspace, dry_run=False) is False
        assert tomllib.loads(config_path.read_text())["project_doc_max_bytes"] > 0
