from typing import Final

CODEX_RULE_MARKER: Final[str] = "# Generated by agent_sync from .agents/rules/"
CODEX_MCP_START_MARKER: Final[str] = "# >>> agent-sync managed MCP servers >>>"
CODEX_MCP_END_MARKER: Final[str] = "# <<< agent-sync managed MCP servers <<<"
MAX_DIFF_LINES: Final[int] = 20
