import logging
from typing import Final

from agent_sync.document import render_front_matter
from agent_sync.errors import AgentSyncError
from agent_sync.generation.context import GenerationContext
from agent_sync.models.output import ArtifactKind, GeneratedFile, GeneratedLink, GeneratedOutput
from agent_sync.models.output import Provider
from agent_sync.providers import PROVIDER_LAYOUTS
from agent_sync.source import resolve_agent_model
from agent_sync.utils import ensure_trailing_newline

GENERATED_FILE_NOTICE: Final[str] = (
    "Generated by [Agent Sync Action](https://github.com/julien777z/agent-sync-action). "
    "Do not edit this file directly."
)

logger = logging.getLogger(__name__)


def generate_agents(context: GenerationContext, provider: Provider) -> list[GeneratedOutput]:
    """Generate one provider's agent files with resolved models."""

    outputs: list[GeneratedOutput] = []
    root = PROVIDER_LAYOUTS[provider].root(context.workspace.root)

    for source in context.agents:
        front_matter = source.front_matter.model_copy(
            update={"model": resolve_agent_model(source.slug, provider, context.source_config)}
        )

        generated_body = "\n\n".join(
            part for part in (f"<!-- {GENERATED_FILE_NOTICE} -->", source.body) if part
        )

        outputs.append(
            GeneratedFile(
                target_path=root / "agents" / f"{source.slug}.md",
                content=render_front_matter(front_matter, generated_body),
                artifact=ArtifactKind.AGENT,
                source_path=source.path,
                provider=provider,
            )
        )

    return outputs


def generate_hooks(context: GenerationContext, provider: Provider) -> list[GeneratedOutput]:
    """Generate one provider's hook files."""

    root = PROVIDER_LAYOUTS[provider].root(context.workspace.root)

    return [
        GeneratedFile(
            target_path=root / "hooks" / source.path.name,
            content=ensure_trailing_newline(source.content),
            artifact=ArtifactKind.HOOK,
            source_path=source.path,
            provider=provider,
            executable=source.executable,
        )
        for source in context.hooks
    ]


def generate_skills(context: GenerationContext, provider: Provider) -> list[GeneratedOutput]:
    """Generate one provider's skill links and native policy metadata."""

    layout = PROVIDER_LAYOUTS[provider]
    root = layout.root(context.workspace.root)
    invocation_policy = layout.explicit_skill_invocation_policy
    outputs: list[GeneratedOutput] = []

    for source in context.skills:
        skill_root = root / "skills" / source.slug

        if not source.front_matter.disable_model_invocation or invocation_policy is None:
            outputs.append(
                GeneratedLink(
                    target_path=skill_root,
                    link_target=source.directory,
                    artifact=ArtifactKind.SKILL,
                    source_path=source.path,
                    provider=provider,
                )
            )

            continue

        metadata_directory = source.directory

        for part in invocation_policy.relative_path.parent.parts:
            metadata_directory /= part

            if (metadata_directory.exists() or metadata_directory.is_symlink()) and not metadata_directory.is_dir():
                raise AgentSyncError(
                    f"Generated skill metadata requires a directory at {metadata_directory}"
                )

        metadata_path = source.directory / invocation_policy.relative_path

        if metadata_path.exists() or metadata_path.is_symlink():
            raise AgentSyncError(
                f"Generated skill metadata is derived from canonical front matter: remove {metadata_path}"
            )

        source_directory = source.directory

        for metadata_part in invocation_policy.relative_path.parts[:-1]:
            outputs.extend(
                GeneratedLink(
                    target_path=(skill_root / source_directory.relative_to(source.directory)) / child.name,
                    link_target=child,
                    artifact=ArtifactKind.SKILL,
                    source_path=source.path,
                    provider=provider,
                )
                for child in sorted(source_directory.iterdir(), key=lambda path: path.name)
                if child.name != metadata_part
            )

            source_directory /= metadata_part

            if not source_directory.is_dir():
                break

        if source_directory.is_dir():
            outputs.extend(
                GeneratedLink(
                    target_path=(skill_root / source_directory.relative_to(source.directory)) / child.name,
                    link_target=child,
                    artifact=ArtifactKind.SKILL,
                    source_path=source.path,
                    provider=provider,
                )
                for child in sorted(source_directory.iterdir(), key=lambda path: path.name)
                if child.name != invocation_policy.relative_path.name
            )

        outputs.append(
            GeneratedFile(
                target_path=skill_root / invocation_policy.relative_path,
                content=invocation_policy.content,
                artifact=ArtifactKind.SKILL,
                source_path=source.path,
                provider=provider,
            )
        )

    return outputs
