import logging
from typing import Final

from agent_sync.document import render_front_matter
from agent_sync.errors import AgentSyncError
from agent_sync.generation.context import GenerationContext
from agent_sync.models.output import ArtifactKind, GeneratedFile, GeneratedLink, GeneratedOutput
from agent_sync.models.output import Provider
from agent_sync.providers import PROVIDER_LAYOUTS
from agent_sync.source import resolve_agent_model
from agent_sync.utils import ensure_trailing_newline

GENERATED_FILE_NOTICE: Final[str] = (
    "Generated by [Agent Sync Action](https://github.com/julien777z/agent-sync-action). "
    "Do not edit this file directly."
)
CODEX_EXPLICIT_INVOCATION_POLICY: Final[str] = "policy:\n" "  allow_implicit_invocation: false\n"

logger = logging.getLogger(__name__)


def generate_agents(context: GenerationContext, provider: Provider) -> list[GeneratedOutput]:
    """Generate one provider's agent files with resolved models."""

    outputs: list[GeneratedOutput] = []
    root = PROVIDER_LAYOUTS[provider].root(context.workspace.root)

    for source in context.agents:
        front_matter = source.front_matter.model_copy(
            update={"model": resolve_agent_model(source.slug, provider, context.source_config)}
        )

        generated_body = "\n\n".join(
            part for part in (f"<!-- {GENERATED_FILE_NOTICE} -->", source.body) if part
        )

        outputs.append(
            GeneratedFile(
                target_path=root / "agents" / f"{source.slug}.md",
                content=render_front_matter(front_matter, generated_body),
                artifact=ArtifactKind.AGENT,
                source_path=source.path,
                provider=provider,
            )
        )

    return outputs


def generate_hooks(context: GenerationContext, provider: Provider) -> list[GeneratedOutput]:
    """Generate one provider's hook files."""

    root = PROVIDER_LAYOUTS[provider].root(context.workspace.root)

    return [
        GeneratedFile(
            target_path=root / "hooks" / source.path.name,
            content=ensure_trailing_newline(source.content),
            artifact=ArtifactKind.HOOK,
            source_path=source.path,
            provider=provider,
            executable=source.executable,
        )
        for source in context.hooks
    ]


def generate_linked_skills(context: GenerationContext, provider: Provider) -> list[GeneratedOutput]:
    """Link one provider to every canonical skill directory."""

    root = PROVIDER_LAYOUTS[provider].root(context.workspace.root)

    return [
        GeneratedLink(
            target_path=root / "skills" / source.slug,
            link_target=source.directory,
            artifact=ArtifactKind.SKILL,
            source_path=source.path,
            provider=provider,
        )
        for source in context.skills
    ]


def generate_codex_skills(context: GenerationContext, provider: Provider) -> list[GeneratedOutput]:
    """Generate Codex skills with native invocation policies."""

    root = PROVIDER_LAYOUTS[provider].root(context.workspace.root)
    outputs: list[GeneratedOutput] = []

    for source in context.skills:
        skill_root = root / "skills" / source.slug

        if not source.front_matter.disable_model_invocation:
            outputs.append(
                GeneratedLink(
                    target_path=skill_root,
                    link_target=source.directory,
                    artifact=ArtifactKind.SKILL,
                    source_path=source.path,
                    provider=provider,
                )
            )

            continue

        metadata_path = source.directory / "agents/openai.yaml"

        if metadata_path.exists():
            raise AgentSyncError(
                f"Codex skill metadata is generated from canonical front matter: remove {metadata_path}"
            )

        outputs.extend(
            GeneratedLink(
                target_path=skill_root / child.name,
                link_target=child,
                artifact=ArtifactKind.SKILL,
                source_path=source.path,
                provider=provider,
            )
            for child in sorted(source.directory.iterdir(), key=lambda path: path.name)
            if child.name not in {"agents"}
        )

        agents_directory = source.directory / "agents"

        if agents_directory.is_dir():
            outputs.extend(
                GeneratedLink(
                    target_path=skill_root / "agents" / child.name,
                    link_target=child,
                    artifact=ArtifactKind.SKILL,
                    source_path=source.path,
                    provider=provider,
                )
                for child in sorted(agents_directory.iterdir(), key=lambda path: path.name)
            )

        outputs.append(
            GeneratedFile(
                target_path=skill_root / "agents/openai.yaml",
                content=CODEX_EXPLICIT_INVOCATION_POLICY,
                artifact=ArtifactKind.SKILL,
                source_path=source.path,
                provider=provider,
            )
        )

    return outputs
