import logging
from typing import Final

from agent_sync.document import render_front_matter
from agent_sync.generation.context import GenerationContext
from agent_sync.models.output import ArtifactKind, GeneratedFile, GeneratedLink, GeneratedOutput
from agent_sync.models.output import Provider
from agent_sync.providers import PROVIDER_LAYOUTS
from agent_sync.source import resolve_agent_model
from agent_sync.utils import ensure_trailing_newline

GENERATED_FILE_NOTICE: Final[str] = (
    "Generated by [Agent Sync Action](https://github.com/julien777z/agent-sync-action). "
    "Do not edit this file directly."
)

logger = logging.getLogger(__name__)


def generate_agents(context: GenerationContext, provider: Provider) -> list[GeneratedOutput]:
    """Generate one provider's agent files with resolved models."""

    outputs: list[GeneratedOutput] = []
    root = PROVIDER_LAYOUTS[provider].root(context.workspace.root)

    for source in context.agents:
        front_matter = source.front_matter.model_copy(
            update={"model": resolve_agent_model(source.slug, provider, context.source_config)}
        )
        generated_body = "\n\n".join(
            part for part in (f"<!-- {GENERATED_FILE_NOTICE} -->", source.body) if part
        )

        outputs.append(
            GeneratedFile(
                target_path=root / "agents" / f"{source.slug}.md",
                content=render_front_matter(front_matter, generated_body),
                artifact=ArtifactKind.AGENT,
                source_path=source.path,
                provider=provider,
            )
        )

    return outputs


def generate_hooks(context: GenerationContext, provider: Provider) -> list[GeneratedOutput]:
    """Generate one provider's hook files."""

    root = PROVIDER_LAYOUTS[provider].root(context.workspace.root)

    return [
        GeneratedFile(
            target_path=root / "hooks" / source.path.name,
            content=ensure_trailing_newline(source.content),
            artifact=ArtifactKind.HOOK,
            source_path=source.path,
            provider=provider,
            executable=source.executable,
        )
        for source in context.hooks
    ]


def generate_skills(context: GenerationContext, provider: Provider) -> list[GeneratedOutput]:
    """Generate one provider's skill links."""

    root = PROVIDER_LAYOUTS[provider].root(context.workspace.root)

    return [
        GeneratedLink(
            target_path=root / "skills" / source.slug,
            link_target=source.directory,
            artifact=ArtifactKind.SKILL,
            source_path=source.path,
            provider=provider,
        )
        for source in context.skills
    ]
