from pathlib import Path
from typing import Final

from agent_sync.document import ensure_trailing_newline, normalize_rule, parse_markdown
from agent_sync.models.document import RuleFrontMatter
from agent_sync.models.output import (
    ArtifactKind,
    GeneratedFile,
    GeneratedLink,
    GeneratedOutput,
    Provider,
)
from agent_sync.models.provider import PROVIDER_LAYOUTS
from agent_sync.slug import validate_slug
from agent_sync.workspace import Workspace

CODEX_RULE_MARKER: Final[str] = "# Generated by agent_sync from .agents/rules/"


def generate_rule_outputs(workspace: Workspace) -> list[GeneratedOutput]:
    """Generate normalized rules, provider links, and root instructions."""

    outputs: list[GeneratedOutput] = []
    rules_dir = workspace.agents_dir / "rules"
    instruction_sections: list[str] = []
    if rules_dir.exists():
        for path in sorted(rules_dir.glob("*.md")):
            slug = validate_slug(path.stem, path)
            content = workspace.read_text(path)
            if content is None:
                continue

            front_matter, body = parse_markdown(content, RuleFrontMatter, str(path))
            if not body:
                continue

            outputs.append(
                GeneratedFile(
                    target_path=path,
                    content=normalize_rule(front_matter, body),
                    artifact=ArtifactKind.RULE,
                    source_path=path,
                )
            )
            outputs.extend(generate_rule_links(workspace, path, slug))
            if front_matter.starlark and front_matter.starlark.strip():
                outputs.append(
                    GeneratedFile(
                        target_path=(
                            PROVIDER_LAYOUTS[Provider.CODEX].root(workspace.root)
                            / "rules"
                            / f"{slug}.rules"
                        ),
                        content=ensure_trailing_newline(
                            f"{CODEX_RULE_MARKER}{path.name}\n{front_matter.starlark.strip()}"
                        ),
                        artifact=ArtifactKind.RULE,
                        source_path=path,
                        provider=Provider.CODEX,
                    )
                )

            instruction_sections.append(render_instruction_section(path, front_matter, body))

    instructions = render_instructions(instruction_sections)
    outputs.append(
        GeneratedFile(
            target_path=workspace.root / "AGENTS.md",
            content=instructions,
            artifact=ArtifactKind.INSTRUCTIONS,
            source_path=rules_dir,
        )
    )

    return outputs


def generate_rule_links(
    workspace: Workspace,
    source_path: Path,
    slug: str,
) -> list[GeneratedOutput]:
    """Generate Claude and Cursor links for one canonical rule."""

    return [
        GeneratedLink(
            target_path=(
                PROVIDER_LAYOUTS[provider].root(workspace.root)
                / "rules"
                / f"{slug}{PROVIDER_LAYOUTS[provider].rule_extension}"
            ),
            link_target=source_path,
            artifact=ArtifactKind.RULE,
            source_path=source_path,
            provider=provider,
        )
        for provider in (Provider.CLAUDE, Provider.CURSOR)
    ]


def render_instruction_section(
    path: Path,
    front_matter: RuleFrontMatter,
    body: str,
) -> str:
    """Render one canonical rule inside the generated root instructions."""

    scope = ""
    if front_matter.globs:
        patterns = (
            [front_matter.globs] if isinstance(front_matter.globs, str) else front_matter.globs
        )
        scope = "> Applies only to files matching: " + ", ".join(
            f"`{pattern}`" for pattern in patterns
        )
    elif not front_matter.always_apply:
        scope = "> Apply this rule only when it is explicitly relevant to the current task."

    return "\n\n".join(
        part for part in (f"<!-- Source: .agents/rules/{path.name} -->", scope, body) if part
    )


def render_instructions(sections: list[str]) -> str:
    """Render the root instruction document from canonical rule sections."""

    header = (
        "# AGENTS.md\n\n"
        "Generated by Agent Sync. Do not edit this file directly.\n\n"
        "The canonical project rules live in `.agents/rules/`.\n"
    )
    content = header if not sections else header + "\n" + "\n\n".join(sections)

    return ensure_trailing_newline(content)
